server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    response-cache-update-interval-ms: 500
    eviction-interval-timer-in-ms: 500

logging:
  level:
      com:
        netflix:
          eureka: 'OFF'
          discovery: 'OFF'

